---
#- name: 允許Node加入集群
#  ignore_errors: yes
#  shell: kubectl certificate approve $(kubectl get csr |awk 'NR!=1{print $1}')

- name: 拷貝YAML檔到Master
  copy: src={{ item }} dest={{ tmp_dir }}
  with_fileglob:
    - "*.yaml"

- name: 部署Calico,Dashboard,CoreDNS,Ingress
  ignore_errors: yes
  shell: |
    cd {{ tmp_dir }}
    for yaml in $(ls *.yaml);do kubectl apply -f $yaml;done

- name: 查看Pod狀態
  shell: kubectl get all --all-namespaces
  register: getall
- debug: var=getall.stdout_lines

- name: 創建Dashboard管理員權杖
  ignore_errors: yes
  shell: |
    kubectl create serviceaccount dashboard-admin -n kubernetes-dashboard
    kubectl create clusterrolebinding dashboard-admin --clusterrole=cluster-admin --serviceaccount=kubernetes-dashboard:dashboard-admin

- name: 獲取Dashboard管理員權杖
  ignore_errors: yes
  shell: |
    web='https://NodeIP:30001'
    token=$(kubectl describe secrets -n kubernetes-dashboard \
    $(kubectl get secret -n kubernetes-dashboard | awk '/dashboard-admin/{print $1}') |awk '/^token/{print $2}')
    echo "訪問位址--->$web"
    echo "權杖內容--->$token"
  register: ui
- name: Kubernetes Dashboard登錄信息
  debug: var=ui.stdout_lines

